### ISSUE TITLE
Uncaught Error: Class 'PhpParser\Node\Scalar\String_' not found

### ISSUE THREAD

**Issue by dugajean** [hanneskod/classtools#9]
```
PHP Fatal error:  Uncaught Error: Class 'PhpParser\Node\Scalar\String_' not found in /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Php5.php:2842
Stack trace:
#0 /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(247): PhpParser\Parser\Php5->reduceRule476()
#1 /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(58): PhpParser\ParserAbstract->parse('<?php\n\nnamespac...')
#2 /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(29): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php5), '<?php\n\nnamespac...')
#3 /Users/username/projects/my-app/vendor/hanneskod/classtools/src/Transformer/Reader.php(61): PhpParser\Parser\Multiple->parse('<?php\n\nnamespac...')
#4 /Users/username/projects/my-app/vendor/hanneskod/classtools/src/Iterator/SplFileInfo.php(53): hanneskod\classtools\Transformer\Reader->__construct('<?php\n\nnamespac...')
#5 /Users/username/Google D in /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Php5.php on line 2842

Fatal error: Uncaught Error: Class 'PhpParser\Node\Scalar\String_' not found in /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Php5.php:2842
Stack trace:
#0 /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(247): PhpParser\Parser\Php5->reduceRule476()
#1 /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(58): PhpParser\ParserAbstract->parse('<?php\n\nnamespac...')
#2 /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Multiple.php(29): PhpParser\Parser\Multiple->tryParse(Object(PhpParser\Parser\Php5), '<?php\n\nnamespac...')
#3 /Users/username/projects/my-app/vendor/hanneskod/classtools/src/Transformer/Reader.php(61): PhpParser\Parser\Multiple->parse('<?php\n\nnamespac...')
#4 /Users/username/projects/my-app/vendor/hanneskod/classtools/src/Iterator/SplFileInfo.php(53): hanneskod\classtools\Transformer\Reader->__construct('<?php\n\nnamespac...')
#5 /Users/username/projects in /Users/username/projects/my-app/vendor/nikic/php-parser/lib/PhpParser/Parser/Php5.php on line 2842
```

It was working fine last time I checked this project (1 week ago). Now when I got back at it, it keeps spitting this errror.

What could this be? That other package is using the correct package version which should've fixed this problem.

Help would be appreciated.

**Comment by hanneskod** [comment]
Hi and thanx for reporting!

Could you please post the code generating this error. What version of php are you using? And what version of classtools?

**Comment by hanneskod** [comment]
Closing this now as there have been no new development.. Please reopen if problem persists!
